controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

when@dev:
    nowo_twig_inspector:
        resource: '@NowoTwigInspectorBundle/Resources/config/routes.yaml'
